version: '3'

services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: postgres
        env_file:
            - globals.env
        volumes:
            - db_data:/var/lib/postgresql/data
    redis:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./globals.env
        ports:
            - '6379:6379'
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        restart: always
        command: npm run dev
        volumes:
            - ./server/src:/usr/app/src
            - /usr/app/node_modules
        env_file:
            - ./globals.env
            - ./server/.env
        depends_on:
            - db
            - redis
        links:
            - redis
            - db

    # compiler:
    #     build:
    #         context: ./compiler
    #         dockerfile: Dockerfile
    #     expose:
    #         - '6969'
    #     volumes:
    #         - ./compiler/src:/usr/app/src

    web:
        build:
            context: ./web
            dockerfile: Dockerfile.dev
        restart: always
        volumes:
            - ./web:/usr/app
            - /usr/app/node_modules
            - /usr/app/.next
        expose:
            - '3000'
        depends_on:
            - server
        links:
            - server
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '80:80'
        depends_on:
            - web
        links:
            - web
            - server
volumes:
    db_data:
