version: '3'

services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: postgres
        env_file:
            - globals.env
        volumes:
            - db_data:/var/lib/postgresql/data
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        restart: always
        command: npm run dev
        volumes:
            - ./server/src:/usr/app/src
            - /usr/app/node_modules
        env_file:
            - ./globals.env
            - ./server/.env
        depends_on:
            - db

    redis:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        volumes:
            - redis_data:/data
        env_file:
            - ./globals.env
        depends_on:
            - server
    web:
        build:
            context: ./web
            dockerfile: Dockerfile.dev
        restart: always
        volumes:
            - ./web:/usr/app
            - /usr/app/node_modules
            - /usr/app/.next
        expose:
            - '3000'
        depends_on:
            - api
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '80:80'
        depends_on:
            - web
volumes:
    db_data:
    redis_data:
